platform :ios, '9.0'
target 'little diary' do

pod 'Masonry'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'TZImagePickerController', '~> 3.2.3'
pod 'SDCycleScrollView'
pod 'TYCyclePagerView'
pod 'BRPickerView'

end